### ISSUE TITLE
Must run create_user as root (at least first time)

### ISSUE THREAD

**Issue by mirw** [Metaswitch/crest#271]
If I run create_user as a non-root user, I get the following error.

```
[cw-aio]ubuntu@cw-aio:~$ /usr/share/clearwater/bin/create_user
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/share/clearwater/clearwater-prov-tools/env/lib/python2.7/site-packages/clearwater_prov_tools-0.1-py2.7.egg/metaswitch/ellis/prov_tools/create_user.py", line 41, in <module>
    from metaswitch.ellis.prov_tools import utils
  File "/usr/share/clearwater/clearwater-prov-tools/env/local/lib/python2.7/site-packages/clearwater_prov_tools-0.1-py2.7.egg/metaswitch/ellis/prov_tools/utils.py", line 46, in <module>
    from metaswitch.ellis.remote import homestead
  File "/usr/share/clearwater/clearwater-prov-tools/env/local/lib/python2.7/site-packages/clearwater_prov_tools-0.1-py2.7.egg/metaswitch/ellis/remote/homestead.py", line 48, in <module>
    from metaswitch.common import utils
  File "build/bdist.linux-x86_64/egg/metaswitch/common/utils.py", line 44, in <module>
  File "build/bdist.linux-x86_64/egg/bcrypt/__init__.py", line 48, in <module>
  File "build/bdist.linux-x86_64/egg/bcrypt/_bcrypt.py", line 7, in <module>
  File "build/bdist.linux-x86_64/egg/bcrypt/_bcrypt.py", line 4, in __bootstrap__
  File "/usr/share/clearwater/clearwater-prov-tools/env/local/lib/python2.7/site-packages/pkg_resources.py", line 896, in resource_filename
    self, resource_name
  File "/usr/share/clearwater/clearwater-prov-tools/env/local/lib/python2.7/site-packages/pkg_resources.py", line 1527, in get_resource_filename
    self._extract_resource(manager, self._eager_to_zip(name))
  File "/usr/share/clearwater/clearwater-prov-tools/env/local/lib/python2.7/site-packages/pkg_resources.py", line 1555, in _extract_resource
    self.egg_name, self._parts(zip_path)
  File "/usr/share/clearwater/clearwater-prov-tools/env/local/lib/python2.7/site-packages/pkg_resources.py", line 962, in get_cache_path
    self.extraction_error()
  File "/usr/share/clearwater/clearwater-prov-tools/env/local/lib/python2.7/site-packages/pkg_resources.py", line 942, in extraction_error
    raise err
pkg_resources.ExtractionError: Can't extract file(s) to egg cache

The following error occurred while trying to extract file(s) to the Python egg
cache:

  [Errno 13] Permission denied: '/home/ubuntu/.python-eggs/py_bcrypt-0.4-py2.7-linux-x86_64.egg-tmp'

The Python egg cache directory is currently set to:

  /home/ubuntu/.python-eggs

Perhaps your account does not have write access to this directory?  You can
change the cache directory by setting the PYTHON_EGG_CACHE environment
variable to point to an accessible directory.
```

If I run it as root, it succeeds.  What's more, it continues to succeed as non-root users once I've run it once as root.

**Comment by mirw** [comment]
@rkd-msw, is this related to the change to how we build/include eggs in Debian packages?

**Comment by rkd-msw** [comment]
Possibly - as a first stab I'd add the --always-unzip flag into the postinst script to see if that removed the need to unpack things into `~/.python-eggs`.

**Comment by graemerobertson** [comment]
I just spun a Homestead node (using a release-94 version of homestead-prov-tools) and ran /usr/share/clearwater/bin/create_user. I got the following warning rather than the error above.

```
/usr/share/clearwater/clearwater-prov-tools/env/local/lib/python2.7/site-packages/pkg_resources.py:991: UserWarning: /home/ubuntu/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
usage: create_user.py [-h] [-k] [-q] [--hsprov IP:PORT] [--plaintext]
                      [--ifc iFC-FILE] [--prefix TWIN_PREFIX]
                      <directory-number>[..<directory-number>] <domain>
                      <password>
create_user.py: error: too few arguments
```

The /home/ubuntu/.python-eggs directory is created the first time this script is run. If it's run as sudo, it's created without group write permissions, and we never see the warning above. If it's not run as sudo, it's created with group write permissions and the warning above is displayed every subsequent time it's run.

I don't know why the effect has changed since this issue was raised, but create_user still needs to be run as sudo the first time it's run.

I've agreed with @JimBunch that this isn't critical and that we'll document that it should always be run as sudo.

@rkd-msw @mirw feel free to read and add any further insights whilst this is fresh in your mind.

**Comment by graemerobertson** [comment]
The ubuntu user's umask is 0002, whilst the sudo user's is 0022 which is the cause of the difference. I don't know much about umasks, so I don't know why there's a difference or what the significance of the difference is. @dtheobald has suggested we can change the umask in the wrapper bash scripts (and presumably change it back again afterwards) to fix this issue. Is that a safe thing to do?

**Comment by dtheobald** [comment]
Changing it in the wrapper will only change it for the duration of that shell and won't affect anything else.

**Comment by mirw** [comment]
Surely the better fix, though, is to fix the unpacking so that neither the ubuntu nor root user writes anything to disk?  (Then it becomes irrelevant what the umask is.)

**Comment by dtheobald** [comment]
That would be better

**Comment by graemerobertson** [comment]
Alas, unpacking python eggs is a mystery beyond mere mortals like us :turtle:

**Comment by dtheobald** [comment]
I agree with that too

**Comment by dtheobald** [comment]
Perhaps changing the umask would be a reasonable short term fix so as to avoid documentation issues pointed out by @JimBunch. Just make that change on the fixes branch, but don't merge to dev and keep this issue opened. Alternatively, I could make the change locally and it'll get disposed of during the next cycle when I pick up the better fix.

**Comment by dtheobald** [comment]
BTW - Here's a list of the files that end up in the ~/.python-eggs directory tree:
```
~/.python-eggs/thrift-0.9.3-py2.7-linux-x86_64.egg-tmp/thrift/protocol/fastbinary.so
~/.python-eggs/msgpack_python-0.4.7-py2.7-linux-x86_64.egg-tmp/msgpack/_packer.so
~/.python-eggs/msgpack_python-0.4.7-py2.7-linux-x86_64.egg-tmp/msgpack/_unpacker.so
~/.python-eggs/py_bcrypt-0.4-py2.7-linux-x86_64.egg-tmp/bcrypt/_bcrypt.so
~/.python-eggs/pycrypto-2.6.1-py2.7-linux-x86_64.egg-tmp/Crypto/Util/strxor.so
~/.python-eggs/pycrypto-2.6.1-py2.7-linux-x86_64.egg-tmp/Crypto/Util/_counter.so
~/.python-eggs/pycrypto-2.6.1-py2.7-linux-x86_64.egg-tmp/Crypto/Cipher/_DES3.so
~/.python-eggs/pycrypto-2.6.1-py2.7-linux-x86_64.egg-tmp/Crypto/Cipher/_ARC4.so
~/.python-eggs/pycrypto-2.6.1-py2.7-linux-x86_64.egg-tmp/Crypto/Cipher/_DES.so
~/.python-eggs/pycrypto-2.6.1-py2.7-linux-x86_64.egg-tmp/Crypto/Cipher/_Blowfish.so
~/.python-eggs/pycrypto-2.6.1-py2.7-linux-x86_64.egg-tmp/Crypto/Cipher/_AES.so
~/.python-eggs/pycrypto-2.6.1-py2.7-linux-x86_64.egg-tmp/Crypto/Cipher/_ARC2.so
~/.python-eggs/pycrypto-2.6.1-py2.7-linux-x86_64.egg-tmp/Crypto/Cipher/_XOR.so
~/.python-eggs/pycrypto-2.6.1-py2.7-linux-x86_64.egg-tmp/Crypto/Cipher/_CAST.so
~/.python-eggs/pycrypto-2.6.1-py2.7-linux-x86_64.egg-tmp/Crypto/Hash/_RIPEMD160.so
~/.python-eggs/pycrypto-2.6.1-py2.7-linux-x86_64.egg-tmp/Crypto/Hash/_SHA384.so
~/.python-eggs/pycrypto-2.6.1-py2.7-linux-x86_64.egg-tmp/Crypto/Hash/_MD2.so
~/.python-eggs/pycrypto-2.6.1-py2.7-linux-x86_64.egg-tmp/Crypto/Hash/_MD4.so
~/.python-eggs/pycrypto-2.6.1-py2.7-linux-x86_64.egg-tmp/Crypto/Hash/_SHA256.so
~/.python-eggs/pycrypto-2.6.1-py2.7-linux-x86_64.egg-tmp/Crypto/Hash/_SHA512.so
~/.python-eggs/pycrypto-2.6.1-py2.7-linux-x86_64.egg-tmp/Crypto/Hash/_SHA224.so
~/.python-eggs/pycrypto-2.6.1-py2.7-linux-x86_64.egg-tmp/Crypto/PublicKey/_fastmath.so
~/.python-eggs/prctl-1.0.1-py2.7-linux-x86_64.egg-tmp/prctl.so
~/.python-eggs/PyYAML-3.11-py2.7-linux-x86_64.egg-tmp/_yaml.so
```

**Comment by mirw** [comment]
@rkd-msw, correct that `--always-unzip` solves this problem.

**Comment by mirw** [comment]
Fixed.
