### ISSUE TITLE
Log spam in Crest

### ISSUE THREAD

**Issue by rkd-msw** [Metaswitch/crest#297]
#### Symptoms

This output is in homer-err.log repeatedly:

```
Unhandled error in Deferred:


Traceback (most recent call last):
  File "/usr/share/clearwater/crest/env/local/lib/python2.7/site-packages/Twisted-15.5.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 434, in errback
    self._startRunCallbacks(fail)
  File "/usr/share/clearwater/crest/env/local/lib/python2.7/site-packages/Twisted-15.5.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 501, in _startRunCallbacks
    self._runCallbacks()
  File "/usr/share/clearwater/crest/env/local/lib/python2.7/site-packages/Twisted-15.5.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "build/bdist.linux-x86_64/egg/telephus/protocol.py", line 224, in reqError

--- <exception caught here> ---
  File "build/bdist.linux-x86_64/egg/telephus/protocol.py", line 218, in reqError

telephus.cassandra.ttypes.InvalidRequestException: InvalidRequestException(why='unconfigured columnfamily ping')
```
#### Impact

Disk fills up, legitimate errors are harder to find.
#### Release and environment

Current master ('Kangaskhan' release)
#### Steps to reproduce

Run Homer. Check /var/log/homer/homer-err.log.

**Comment by rkd-msw** [comment]
Looks like it's related to #287 + #291.
