### ISSUE TITLE
Crest may throw ZeroDivisionError when multiple requests get stacked up

### ISSUE THREAD

**Issue by richardwhiuk** [Metaswitch/crest#301]
#### Symptoms

Attempted to sync Ellis's database. Ellis made a huge number of requests to Homestead, which caused it to become overloaded. During the overload, Homestead threw ZeroDivisionErrors:

```
09-09-2016 09:50:29.577 UTC ERROR base.py:341: Traceback (most recent call last):
  File "/usr/share/clearwater/crest/env/local/lib/python2.7/site-packages/Twisted-16.3.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 393, in callback
    self._startRunCallbacks(result)
  File "/usr/share/clearwater/crest/env/local/lib/python2.7/site-packages/Twisted-16.3.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 501, in _startRunCallbacks
    self._runCallbacks()
  File "/usr/share/clearwater/crest/env/local/lib/python2.7/site-packages/Twisted-16.3.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/share/clearwater/crest/env/local/lib/python2.7/site-packages/Twisted-16.3.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 1184, in gotResult
    _inlineCallbacks(r, g, deferred)
--- <exception caught here> ---
  File "/usr/share/clearwater/crest/env/local/lib/python2.7/site-packages/Twisted-16.3.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)
  File "/usr/share/clearwater/homestead/python/packages/homestead_prov-0.1-py2.7.egg/metaswitch/homestead_prov/provisioning/handlers/public.py", line 163, in get
    self.send_json({JSON_PRIVATE_IDS: private_ids})
  File "/usr/share/clearwater/crest/env/lib/python2.7/site-packages/crest-0.1-py2.7.egg/metaswitch/crest/api/base.py", line 421, in send_json
    self.finish()
  File "/usr/share/clearwater/crest/env/local/lib/python2.7/site-packages/cyclone-1.0-py2.7.egg/cyclone/web.py", line 652, in finish
    return self.on_finish()
  File "/usr/share/clearwater/crest/env/lib/python2.7/site-packages/crest-0.1-py2.7.egg/metaswitch/crest/api/base.py", line 279, in on_finish
    loadmonitor.update_latency(latency)
  File "/usr/share/clearwater/crest/env/lib/python2.7/site-packages/crest-0.1-py2.7.egg/metaswitch/crest/api/base.py", line 176, in update_latency
    accepted_percent = 100 * (float(self.accepted) / float(self.accepted + self.rejected))
exceptions.ZeroDivisionError: float division by zero
```
#### Impact

This prevents overload checking working correctly, potentially blocking legitimate requests
#### Release and environment

AWS EC2 deployment spun up using Chef - Sprint Missingno 
#### Steps to reproduce

Run sync_database.py on Ellis

**Comment by richardwhiuk** [comment]
Initial analysis suggests the following is happening.

Large number of parallel requests arrives at homestead-prov. Large number of requests are accepted, incrementing self.accepted, with some being rejected, incrementing self.rejected.

These requests then finish all virtually simultaneously - probably due to some sort of cache effect.

 - Each request runs update_latency, decreasing the adjust count.
 - For the first 19 requests, nothing happens.
 - On the 20th request, adjust_count is 0, and adjust_count is reset to 20, and self.accepted is reset to 0.  -  - On the 40th request, adjust_count is again 0, and the division fails with a ZeroDivisionError. This doesn't reset anything
- All subsequent requests, until a new request is accepted/rejected, cause ZDEs.

**Comment by sebrexmetaswitch** [comment]
Fixed in linked PR, now merged to dev too https://github.com/Metaswitch/crest/commit/4368223ba4b377e5aa430875b1c9d41b00841892
