### ISSUE TITLE
Exceptions in the homer logs when trying to change a subscriber config

### ISSUE THREAD

**Issue by eleanor-merry** [Metaswitch/crest#84]
This is seen when trying to change the subscriber's config through ellis. The subscriber's config does actually get updated though. 

Trace:
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
  File "/usr/share/clearwater/homer/env/local/lib/python2.7/site-packages/Twisted-12.3.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 381, in callback
    self._startRunCallbacks(result)
  File "/usr/share/clearwater/homer/env/local/lib/python2.7/site-packages/Twisted-12.3.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 489, in _startRunCallbacks
    self._runCallbacks()
  File "/usr/share/clearwater/homer/env/local/lib/python2.7/site-packages/Twisted-12.3.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 576, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/share/clearwater/homer/env/local/lib/python2.7/site-packages/Twisted-12.3.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 1127, in gotResult
    _inlineCallbacks(r, g, deferred)
--- <exception caught here> ---
  File "/usr/share/clearwater/homer/env/local/lib/python2.7/site-packages/Twisted-12.3.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 1071, in _inlineCallbacks
    result = g.send(result)
  File "/usr/share/clearwater/homer/env/local/lib/python2.7/site-packages/crest-0.1-py2.7.egg/metaswitch/crest/api/passthrough.py", line 91, in put
    self.finish({})
  File "/usr/share/clearwater/homer/env/local/lib/python2.7/site-packages/cyclone-1.0-py2.7.egg/cyclone/web.py", line 620, in finish
    raise RuntimeError("finish() called twice.  May be caused "
exceptions.RuntimeError: finish() called twice.  May be caused by using async operations without the @asynchronous decorator.

The error is caused by the put function in passthrough.py yielding a deferred before calling finish. put then returns the deferred to cyclone immediately, which calls self.finish. When put then resumes after the yield, self.finish then gets called twice. This is (possibly) only an issue for the put as it's been subclassed. 

(in passthrough.py)
    @defer.inlineCallbacks
    def put(self, row):
        yield self.cass.insert(column_family=self.table, key=row, column=self.column, value=self.request.body)
        self.finish({})

(in simservs.py)
class SimservsHandler(PassthroughHandler):
    """
Handler that validates simservs documents before storing them
"""
    @xsd.validate(SCHEMA_PATH)
    def put(self, *args):
        return PassthroughHandler.put(self, *args)

**Comment by rkd-msw** [comment]
I can't repro this on the current code. However, if I revert either https://github.com/Metaswitch/crest/commit/dc7b9d61bcac4933909f650957d2456517771750 or https://github.com/Metaswitch/crest/commit/e74d892a9aa48efaaeef7d823eaf4dde1f601ab0 (which went in the day after this issue was raised), I can repro:

```
$ cat homer-err.log
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
  File "/usr/share/clearwater/homer/env/local/lib/python2.7/site-packages/Twisted-12.3.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 381, in callback
    self._startRunCallbacks(result)
  File "/usr/share/clearwater/homer/env/local/lib/python2.7/site-packages/Twisted-12.3.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 489, in _startRunCallbacks
    self._runCallbacks()
  File "/usr/share/clearwater/homer/env/local/lib/python2.7/site-packages/Twisted-12.3.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 576, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/share/clearwater/homer/env/local/lib/python2.7/site-packages/Twisted-12.3.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 1127, in gotResult
    _inlineCallbacks(r, g, deferred)
--- <exception caught here> ---
  File "/usr/share/clearwater/homer/env/local/lib/python2.7/site-packages/Twisted-12.3.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 1071, in _inlineCallbacks
    result = g.send(result)
  File "/usr/share/clearwater/homer/env/local/lib/python2.7/site-packages/crest-0.1-py2.7.egg/metaswitch/crest/api/passthrough.py", line 91, in put
    self.finish({})
  File "/usr/share/clearwater/homer/env/local/lib/python2.7/site-packages/cyclone-1.0-py2.7.egg/cyclone/web.py", line 620, in finish
    raise RuntimeError("finish() called twice.  May be caused "
exceptions.RuntimeError: finish() called twice.  May be caused by using async operations without the @asynchronous decorator.
```

so it looks like one/both of those fixed this. @eleanor-merry, happy to close?
